### ISSUE TITLE
outdated packages

### ISSUE THREAD

**Issue by digcat** [linodeproservices/mariadb-galera-ansible#1]
Hi, came across your galera project, thought I'd give it a whirl.

I came  across a few issues, first a few easy ones, I needed to do a pip3 install polling and pip3 install wheel, to get the provision working cleanly.

When I came to the ansible-playbook -i hosts site.yml
All went well until it tried to install the mariadb packages, when I got
 install 'mariadb-server' 'mariadb-backup' -o APT::Install-Recommends=yes' failed: E: Failed to fetch http://mirrors.linode.com/ubuntu/pool/universe/m/mariadb-10.3/mariadb-common_10.3.25-0ubuntu0.20.04.1_all.deb  404  Not Found [IP: 2400:8907:1::ac69:a422 80]\nE: Failed to fetch http://mirrors.linode.com/ubuntu/pool/universe/m/mariadb-10.3/mariadb-client-core-10.3_10.3.25-0ubuntu0.20.04.1_amd64.deb

Looking at where its trying to get these, it looks like those 10.3.25 packages are no longer there, and now its 10.3.29.

From what I can see these must be defined in the galaxy packages ?  but its preventing this from working.  Thanks for your efforts in releasing this.

Daren

**Comment by rylabs-billy** [comment]
Hi Daren,

This should be resolved with [4c6a690](https://github.com/linodeproservices/mariadb-galera-ansible/commit/4c6a690ca82ccb09ea132827f01c01e3312533f2). 
 
The polling package isn't required here. It looks like the issue on your end was the missing `wheel` package that doesn't ship with `venv` by default (as noted [here](https://github.com/pypa/pip/issues/8102)). Use `virtualenv` instead and it should work. I updated the README accordingly. The 404s were happening because of a syntax error in the `apt update` task. I resolved that and also forced IPv4 transport.

Thanks for bringing this to my attention!

Billy

**Comment by digcat** [comment]
Hi Billy,
Many thanks for taking your time to review this.  I switched over to virtualenv,(20.0.17) however I'm still seeing the missing polling package, which I needed to use pip3 install polling to get around.  After that though it all ran through well, and I ended up with a working cluster !!  
A couple of minor things are the warnings, one for using tags as a variable name, and a warning on group for using -
One other thing which would be good, is to force a reboot on all the nodes, as they are all left waiting for a restart.
But all that said, great work !!

cheers
Daren

**Comment by rylabs-billy** [comment]
Hi Daren,

I'm glad to hear it worked out for you!

That said, I'll soon be pushing some improvements to this playbook after I get some other things out the door. I also just merged [67fb280](https://github.com/linodeproservices/mariadb-galera-ansible/commit/67fb28076f5ddc4aab3d1ef7d386c85df6b13952) to remove all those warnings, except for the first one...

> [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

This just means that Ansible didn't find any inventory in the default location at `/etc/ansible/hosts`. Since this playbook dynamically writes your inventory to the `hosts` file, this message is to be expected. If you were to run `provision.yml` a second time and pass the `hosts` file to it, that message is gone because Ansible found existing inventory.

Cheers,
Billy
